# These are supported funding model platforms.
github: [AmaLS367]

# Referral links that can support the project.
custom:
  - https://www.bybit.com/invite?ref=6ANMX04
  - https://www.binance.com/referral/earn-together/refer2earn-usdc/claim?hl=ru&ref=GRO_28502_1KDBV&utm_source=referral_entrance
